### ISSUE TITLE
How to run this on a different port?

### ISSUE THREAD

**Issue by jessicaverba** [gokhanmeteerturk/reddit-scheduler-be#1]
I am using port 8080 for something else. How can I change the port? I am using docker. I changed dockerfile but didn't work.

**Comment by gokhanmeteerturk** [comment]
If you only need to change the port used on the host machine, you don't need to change the Dockerfile at all. Just map the container's port to a different port on host(like 8081) in docker-compose.yaml:

```
    ports:
      - "8081:8080"
```
